
CREATE DATABASE outrage;


GRANT ALL PRIVILEGES ON DATABASE outrage TO postgres;


GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO postgres;


GRANT ALL PRIVILEGES ON SCHEMA public TO postgres;


GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO postgres;