version: '3'

services:
  outrage_db:
    image: 'postgres:9.6.3'
    environment:
      - POSTGRES_USER=postgres
    ports:
      - '55:5432'
    volumes:
      - ./outrage_db/db_setup:/docker-entrypoint-initdb.d
    networks:
      - PBOG


  outrage_scraper:
     build:
       context: ./outrage_scraper
       dockerfile: Dockerfile
     ports:
       - '66:66'
     volumes:
       - ./outrage_scraper:/app/outrage_scraper
     networks:
       - PBOG


  outrage_display:
      build:
        context: ./outrage_display
        dockerfile: Dockerfile
      ports:
        - '5000:5000'
      volumes:
        - ./outrage_display:/app/outrage_display
      networks:
        - PBOG        

networks:
  PBOG:



