version: '3'

services:
  outrage_db:
    image: 'postgres:9.6.3'
    environment:
      - POSTGRES_USER=outrage
    ports:
      - '55:5432'
    volumes:
      - ./outrage_db/db_setup:/docker-entrypoint-initdb.d
    networks:
      - PBOG     

networks:
  PBOG:



