url_master_list = {'abingdon+herald': 'www.heraldseries.co.uk', 'accrington+observer': 'www.accringtonobserver.co.uk',
                   'northumberland+gazette': 'www.northumberlandgazette.co.uk', 'alton+herald': 'www.altonherald.com',
                   'andover+advertiser': 'www.andoveradvertiser.co.uk', 'pulmans+weekly+news': 'www.devonlive.com',
                   'view+from+axminster': 'edition.pagesuite-professional.co.uk',
                   'bucks+herald': 'www.bucksherald.co.uk', 'banbury+guardian': 'www.banburyguardian.co.uk',
                   'the+barnsley+chronicle': 'www.barnsleychronicle.com', 'the+independent': 'www.independent.co.uk',
                   'north+west+evening+mail': 'www.nwemail.co.uk', 'basildon+yellow+advertiser': 'www.yellowad.co.uk',
                   'basingstoke+gazette': 'www.basingstokegazette.co.uk',
                   'basingstoke+observer': 'www.basingstokeobserver.co.uk',
                   'bedfordshire+on+sunday': 'www.bedfordtoday.co.uk',
                   'bicester+advertiser': 'www.bicesteradvertiser.net', 'bicester+review': 'www.bicesteradvertiser.net',
                   'birmingham+post': 'www.birminghampost.co.uk', 'sports+argus': 'en.wikipedia.org',
                   'sunday+mercury': 'www.birminghammail.co.uk', 'blackpool+gazette': 'www.blackpoolgazette.co.uk',
                   'bolton+news': 'www.theboltonnews.co.uk', 'bootle+champion': 'www.champnews.com',
                   'boston+standard': 'www.bostonstandard.co.uk', 'boston+target': 'www.lincolnshirelive.co.uk',
                   'bourne+local': 'www.bournelocal.co.uk', 'stamford+mercury': 'www.stamfordmercury.co.uk',
                   'bracknell+news': '', 'bracknell+midweek': 'bracknellmidweeklge.play-cricket.com',
                   'bracknell+standard': 'www.inyourarea.co.uk', 'the+bradfordian': 'www.bradfordgrammar.com',
                   'telegraph+and+argus': 'www.thetelegraphandargus.co.uk', 'brentwood+gazette': 'www.essexlive.news',
                   'bridlington+free+press': 'www.bridlingtonfreepress.co.uk',
                   'the+bridport+news': 'www.bridportnews.co.uk', 'brighouse+echo': 'www.brighouseecho.co.uk',
                   'bristol+evening+post': 'www.bristolpost.co.uk', 'bristol+observer': 'bristolobserver.com',
                   'bromsgrove+standard': 'bromsgrovestandard.co.uk', 'burnley+express': 'www.burnleyexpress.net',
                   'burton+mail': 'www.staffordshire-live.co.uk', 'bury+times': 'www.burytimes.co.uk',
                   'bury+free+press': 'www.buryfreepress.co.uk', 'buxton+advertiser': 'www.buxtonadvertiser.co.uk',
                   'cambridge+evening+news': 'www.cambridge-news.co.uk', 'canterbury+times': 'www.kentlive.news',
                   'kentish+gazette': 'www.kentonline.co.uk', 'news+and+star': 'www.newsandstar.co.uk',
                   'cumberland+news': 'www.newsandstar.co.uk', 'cumbrian+gazette': 'www.thewestmorlandgazette.co.uk',
                   'bucks+examiner': 'www.bucksfreepress.co.uk', 'cheshunt': 'en.wikipedia.org',
                   'chester+and+district+standard': 'www.chesterstandard.co.uk',
                   'chester+chronicle': 'www.cheshire-live.co.uk', 'chester+evening+leader': 'www.leaderlive.co.uk',
                   'chester+mail': 'portal.chester.ac.uk', 'chew+valley+gazette': 'www.chewvalleygazette.co.uk',
                   'chichester+observer': 'www.chichester.co.uk', 'chorley+citizen': 'www.chorleycitizen.co.uk',
                   'chorley+guardian': 'www.chorley-guardian.co.uk', 'essex+county+standard': 'www.gazette-news.co.uk',
                   'congleton+chronicle': 'www.chronicleseries.com', 'cotswold+journal': 'www.cotswoldjournal.co.uk',
                   'coventry+advertiser': 'www.coventryadvertiser.co.uk', 'coventry+observer': 'coventryobserver.co.uk',
                   'coventry+telegraph': 'www.coventrytelegraph.net', 'crawley+news': '',
                   'crawley+observer': 'www.crawleyobserver.co.uk', 'crewe+chronicle': 'www.crewechronicle.co.uk',
                   'crewe+guardian': 'www.creweguardian.co.uk', 'south+cheshire+mail': 'www.southcheshireccg.nhs.uk',
                   'croydon+advertiser': 'www.croydonadvertiser.co.uk',
                   'croydon+guardian': 'www.yourlocalguardian.co.uk', 'croydon+post': '',
                   'daventry+express': 'www.daventryexpress.co.uk',
                   'derby+evening+telegraph': 'www.derbytelegraph.co.uk', 'derby+express': 'www.derby-exp.co.uk',
                   'derby+trader': 'en.wikipedia.org', 'dewsbury+reporter': 'www.dewsburyreporter.co.uk',
                   'diss+express': 'www.dissexpress.co.uk', 'doncaster+free+press': 'www.doncasterfreepress.co.uk',
                   'droitwich+standard': 'droitwichstandard.co.uk', 'dudley+news': 'www.dudleynews.co.uk',
                   'express+and+star': 'www.expressandstar.com', 'durham+times': 'www.thenorthernecho.co.uk',
                   'eastbourne+gazette': 'www.eastbourneherald.co.uk',
                   'eastbourne+herald': 'www.eastbourneherald.co.uk', 'evesham+journal': 'www.eveshamjournal.co.uk',
                   'express+and+echo': 'www.devonlive.com', 'exmouth+journal': 'www.exmouthjournal.co.uk',
                   'farnborough+news': 'www.getsurrey.co.uk', 'star+courier': 'www.holdthefrontpage.co.uk',
                   'faversham+news': 'www.kentonline.co.uk', 'faversham+times': 'www.kentonline.co.uk',
                   'fleetwood+weekly+news': 'www.fleetwoodtoday.co.uk', 'formby+visitor': 'www.southportvisiter.co.uk',
                   'gainsborough+standard': 'www.gainsboroughstandard.co.uk',
                   'garstang+courier': 'www.garstangcourier.co.uk', 'glossop+advertiser': 'glossopchronicle.com',
                   'glossop+chronicle': 'glossopchronicle.com', 'glossop+gazette': 'glossopgazette.co.uk',
                   'gloucester+citizen': 'www.gloucestershirelive.co.uk',
                   'gloucestershire+echo': 'www.gloucestershirelive.co.uk',
                   'stroud+life': 'www.gloucestershirelive.co.uk', 'goole+times': 'www.gooletimes.info',
                   'grantham+journal': 'www.granthamjournal.co.uk', 'grimsby+telegraph': 'www.grimsbytelegraph.co.uk',
                   'surrey+advertiser': 'www.getsurrey.co.uk', 'halifax+evening+courier': 'www.halifaxcourier.co.uk',
                   'harlow+scene': 'licklist.co.uk', 'harlow+star': 'www.essexlive.news',
                   'harrogate+advertiser': 'www.harrogateadvertiser.co.uk',
                   'hartlepool+mail': 'www.hartlepoolmail.co.uk',
                   'hastings+independent+press': 'www.hastingsindependentpress.co.uk',
                   'hebden+bridge+times': 'www.hebdenbridgetimes.co.uk',
                   'hemel+hempstead+gazette': 'www.hemeltoday.co.uk', 'herald+express': 'www.devonlive.com',
                   'henley+standard': 'www.henleystandard.co.uk', 'hereford+times': 'www.herefordtimes.com',
                   'hertfordshire+mercury': 'www.hertfordshiremercury.co.uk',
                   'watford+observer': 'www.watfordobserver.co.uk', 'welwyn+hatfield+times': 'www.whtimes.co.uk',
                   'heywood+advertiser': 'www.manchestereveningnews.co.uk',
                   'hexham+courant': 'www.hexham-courant.co.uk', 'holme+valley+express': 'en.wikipedia.org',
                   'midweek+herald': 'www.midweekherald.co.uk', 'view+from+honiton': 'www.devonlive.com',
                   'hucknall+and+bulwell+dispatch': 'www.hucknalldispatch.co.uk',
                   'colne+valley+chronicle': 'www.europages.co.uk',
                   'huddersfield+daily+examiner': 'www.examinerlive.co.uk',
                   'huddersfield+weekly+news': 'www.examinerlive.co.uk', 'ilkley+gazette': 'www.ilkleygazette.co.uk',
                   'sheerness+times+guardian': 'www.kentonline.co.uk', 'sheppey+gazette': 'www.kentonline.co.uk',
                   'isle+of+wight+county+press': 'www.iwcp.co.uk', 'wight+insight': 'www.insightguides.com',
                   'keighley+news': 'www.keighleynews.co.uk', 'westmorland+gazette': 'www.thewestmorlandgazette.co.uk',
                   'hull+daily+mail': 'www.hulldailymail.co.uk', 'kingston+guardian': 'www.yourlocalguardian.co.uk',
                   'surrey+comet': 'www.surreycomet.co.uk', 'knutsford+guardian': 'www.knutsfordguardian.co.uk',
                   'lancaster+guardian': 'www.lancasterguardian.co.uk', 'langport+leveller': 'langport.life',
                   'leeds+express': 'www.express.co.uk', 'yorkshire+evening+post': 'www.yorkshireeveningpost.co.uk',
                   'yorkshire+post': 'www.yorkshirepost.co.uk', 'the+yorkshire+reporter': 'yorkshirereporter.co.uk',
                   'leek+post+and+times': 'www.stokesentinel.co.uk', 'your+leek+paper': 'www.stokesentinel.co.uk',
                   'leicester+mercury': 'www.leicestermercury.co.uk',
                   'leicester+advertiser': 'www.leicesteradvertiser.net', 'leigh+journal': 'www.leighjournal.co.uk',
                   'leigh+reporter': 'www.leighobserver.co.uk', 'leyland+guardian': 'www.leylandguardian.co.uk',
                   'lichfield+mercury': 'www.birminghammail.co.uk', 'liverpool+daily+post': 'www.dailypost.co.uk',
                   'liverpool+echo': 'www.liverpoolecho.co.uk', 'mersey+reporter': 'www.merseyreporter.com',
                   'bexley+mercury': 'www.bexleytimes.co.uk', 'bexley+times': 'www.bexleytimes.co.uk',
                   'brixton+bugle': 'www.brixtonblog.com', 'camden+gazette': 'camdennewjournal.com',
                   'camden+new+journal': 'camdennewjournal.com', 'ealing+gazette': 'www.getwestlondon.co.uk',
                   'ealing+leader': 'www.getwestlondon.co.uk', 'ealing+informer': 'www.ealingtimes.co.uk',
                   'east+london+advertiser': 'www.eastlondonadvertiser.co.uk',
                   'enfield+advertiser': 'www.enfieldindependent.co.uk',
                   'enfield+gazette': 'www.enfieldindependent.co.uk', 'evening+standard': 'www.standard.co.uk',
                   'hackney+gazette': 'www.hackneygazette.co.uk', 'hampstead+and+highgate+express': 'www.hamhigh.co.uk',
                   'haringey+advertiser': 'www.haringey.gov.uk', 'harrow+informer': 'www.harrowtimes.co.uk',
                   'harrow+leader': 'www.harrowtimes.co.uk', 'havering+yellow+advertiser': 'www.yellowad.co.uk',
                   'hounslow+borough+chronicle': 'www.getwestlondon.co.uk',
                   'ilford+recorder': 'www.ilfordrecorder.co.uk', 'islington+gazette': 'www.islingtongazette.co.uk',
                   'kilburn+times': 'www.kilburntimes.co.uk', 'london+lite': 'en.wikipedia.org',
                   'the+londoner': 'www.thelondoner.me', 'muswell+hill+journal': 'muswellhilljournal24.co.uk',
                   'newham+recorder': 'www.newhamrecorder.co.uk',
                   'richmond+and+twickenham+times': 'www.richmondandtwickenhamtimes.co.uk',
                   'romford+and+havering+post': 'www.archanthub.co.uk',
                   'south+london+press': 'www.londonnewsonline.co.uk', 'staines+informer': 'www.getsurrey.co.uk',
                   'staines+leader': 'media.info', 'surrey+herald': 'www.getsurrey.co.uk',
                   'surrey+mirror+advertiser': 'www.getsurrey.co.uk', 'sutton+guardian': 'www.yourlocalguardian.co.uk',
                   'uxbridge+gazette': 'www.getwestlondon.co.uk', 'waltham+forest+news': 'www.guardian-series.co.uk',
                   'wanstead+and+woodford+guardian': 'www.guardian-series.co.uk',
                   'loughborough+echo': 'www.leicestermercury.co.uk', 'loughborough+mail': 'www.lboro.ac.uk',
                   'loughborough+trader+xtra': 'www.abc.org.uk', 'loughton+guardian': 'www.eppingforestguardian.co.uk',
                   'luton+on+sunday': 'www.lutontoday.co.uk', 'view+from+lyme+regis': 'lyme-online.co.uk',
                   'the+macclesfield+express': 'www.macclesfield-live.co.uk',
                   'the+macclesfield+times': 'www.manchestereveningnews.co.uk',
                   'maidenhead+advertiser': 'www.maidenhead-advertiser.co.uk',
                   'malvern+gazette': 'www.malverngazette.co.uk',
                   'manchester+evening+news': 'www.manchestereveningnews.co.uk',
                   'market+drayton+advertiser': 'www.shropshirestar.com', 'harborough+mail': 'www.harboroughmail.co.uk',
                   'market+rasen+mail': 'www.marketrasenmail.co.uk',
                   'middleton+guardian': 'www.manchestereveningnews.co.uk', 'onemk': 'en.wikipedia.org',
                   'west+somerset+free+press': 'www.wsfp.co.uk', 'newbury+weekly+news': 'www.newburytoday.co.uk',
                   'evening+chronicle': 'www.chroniclelive.co.uk', 'sunday+sun': 'www.chroniclelive.co.uk',
                   'newtownabbey+times': 'www.newtownabbeytoday.co.uk',
                   'northampton+mercury': 'www.britishnewspaperarchive.co.uk',
                   'northwich+guardian': 'www.northwichguardian.co.uk', 'north+yorkshire+news': '',
                   'norwich+evening+news': 'www.eveningnews24.co.uk', 'newark+advertiser': 'www.newarkadvertiser.co.uk',
                   'nottingham+evening+post': 'www.nottinghampost.com', 'worksop+guardian': 'www.worksopguardian.co.uk',
                   'oldham+advertiser': 'www.manchestereveningnews.co.uk',
                   'oldham+evening+chronicle': 'www.oldham-chronicle.co.uk',
                   'ormskirk+and+west+lancashire+advertiser': 'www.southportvisiter.co.uk',
                   'ormskirk+and+west+lancashire+champion': 'www.champnews.com', 'oxford+mail': 'www.oxfordmail.co.uk',
                   'oxford+star': 'india.oup.com', 'oxford+times': 'www.oxfordtimes.co.uk',
                   'cumberland+and+westmorland+herald': 'www.cwherald.com',
                   'peterlee+star': 'www.thenorthernecho.co.uk', 'plymouth+evening+herald': 'www.plymouthherald.co.uk',
                   'western+morning+news': 'thisiswesternmorningnews.co.uk', 'sports+mail': 'www.dailymail.co.uk',
                   'prestwich+and+whitefield+guide': 'www.prestwichandwhitefieldguide.co.uk',
                   'reading+chronicle': 'www.readingchronicle.co.uk', 'reading+evening+post': 'www.getreading.co.uk',
                   'retford+times': 'www.lincolnshirelive.co.uk',
                   'retford+trader+and+guardian': 'www.retfordtoday.co.uk', 'ripon+gazette': 'www.ripongazette.co.uk',
                   'rochdale+observer': 'www.rochdaleonline.co.uk', 'romford+recorder': 'www.romfordrecorder.co.uk',
                   'romsey+advertiser': 'www.romseyadvertiser.co.uk',
                   'rotherham+advertiser': 'www.rotherhamadvertiser.co.uk',
                   'rugby+advertiser': 'www.rugbyadvertiser.co.uk', 'rugby+observer': 'rugbyobserver.co.uk',
                   'salford+advertiser': 'www.manchestereveningnews.co.uk',
                   'scarborough+evening+news': 'www.thescarboroughnews.co.uk',
                   'scarborough+mercury': 'www.thescarboroughnews.co.uk',
                   'scunthorpe+telegraph': 'www.grimsbytelegraph.co.uk', 'selby+post': '',
                   'selby+star': 'www.thebigeat.com', 'selby+times': 'www.gooletimes.info',
                   'seaford+gazette': 'www.eastbourneherald.co.uk', 'sheffield+star': '',
                   'shrewsbury+chronicle': 'www.shropshirestar.com', 'east+kent+gazette': 'www.kentonline.co.uk',
                   'sleaford+standard': 'www.sleafordstandard.co.uk', 'sleaford+target': 'www.lincolnshirelive.co.uk',
                   'solent+times': 'www.solenttimes.co.uk', 'slough+express': 'www.sloughexpress.co.uk',
                   'somerton+sentinel': 'en-gb.facebook.com', 'shields+gazette': 'www.shieldsgazette.com',
                   'southport+champion': 'www.champnews.com', 'southport+reporter': 'www.southportreporter.com',
                   'southport+visiter': 'www.southportvisiter.co.uk',
                   'sheffield+telegraph': 'www.sheffieldtelegraph.co.uk',
                   'stockport+express': 'www.manchestereveningnews.co.uk',
                   'stowmarket+mercury': 'www.stowmarketmercury.co.uk', 'stratford+herald': 'www.stratford-herald.com',
                   'stratford+observer': 'stratfordobserver.co.uk',
                   'stroud+news+and+journal': 'www.stroudnewsandjournal.co.uk',
                   'sunderland+echo': 'www.sunderlandecho.com', 'sutton+coldfield+observer': 'www.birminghammail.co.uk',
                   'swindon+advertiser': 'www.swindonadvertiser.co.uk', 'swindon+star': 'www.gazetteandherald.co.uk',
                   'tameside+advertiser': 'www.manchestereveningnews.co.uk',
                   'tameside+reporter': 'tamesidereporter.com', 'tamworth+herald': 'www.birminghammail.co.uk',
                   'the+somerset+county+gazette': 'www.somersetcountygazette.co.uk',
                   'the+taunton+times': 'en.wikipedia.org', 'melton+times': 'www.meltontimes.co.uk',
                   'wakefield+express': 'www.wakefieldexpress.co.uk',
                   'wakefield+express+extra': 'www.wakefieldexpress.co.uk',
                   'warminster+journal': 'www.wiltshiretimes.co.uk',
                   'warrington+guardian': 'www.warringtonguardian.co.uk', 'wetherby+news': 'www.wetherbynews.co.uk',
                   'whitby+gazette': 'www.whitbygazette.co.uk', 'whitchurch+herald': 'www.whitchurchherald.co.uk',
                   'widnes+weekly+news': 'www.runcornandwidnesworld.co.uk',
                   'widnes+world': 'www.runcornandwidnesworld.co.uk', 'wigan+evening+post': 'www.wigantoday.net',
                   'wigan+observer': 'www.wigantoday.net', 'wigan+reporter': 'www.wigantoday.net',
                   'gazette+and+herald': 'www.gazetteandherald.co.uk', 'wiltshire+times': 'www.wiltshiretimes.co.uk',
                   'winchester+today': 'www.winchestertoday.co.uk', 'wirral+globe': 'www.wirralglobe.co.uk',
                   'wirral+news': 'www.wirralglobe.co.uk', 'the+wokingham+paper': 'www.wokinghampaper.com',
                   'worcester+news': 'www.worcesternews.co.uk',
                   'kidderminster+shuttle': 'www.kidderminstershuttle.co.uk',
                   'worksop+trader': 'www.worksopguardian.co.uk', 'western+gazette': 'www.somersetlive.co.uk',
                   'york+press': 'www.yorkpress.co.uk'}
